#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#
[tool.robotpy]
# Version of robotpy this project depends on
robotpy_version = "2025.2.1.2"
# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    "all",
]
# Other pip packages to install
requires = [
    "numpy==2.2.1.dev0; platform_machine == 'roborio'",
]






