[tool.robotpy]
# Version of RobotPy your project depends on
robotpy_version = "2025.2.1.0"

# Extra RobotPy components to install
robotpy_extras = [
    "all"
    # "apriltag"
    # "commands2"
    # "cscore"
    # "navx"
    # "pathplannerlib"
    # "phoenix5"
    # "phoenix6"
    # "playingwithfusion"
    # "rev"
    # "romi"
    # "sim"
]

# Other pip packages to install
requires = []
